name: Build & Deploy NuGet

# doc: https://docs.github.com/en/actions
# variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
  
jobs:

  version_increment:
    uses: weknow-network/weknow-workflows/.github/workflows/dotnet-increment-version.yml@main
      
  build-nuget:
    uses: weknow-network/weknow-workflows/.github/workflows/dotnet-build-deploy-public-nuget.yml@main
    needs: [version_increment]
    secrets:
      NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}
    with:
      build-config: Release
      dotnet-version: 5.x
      include-prerelease: false


